
export ZSH="$HOME/.oh-my-zsh"

#THEME
ZSH_THEME="half-life"

#TITLE
DISABLE_AUTO_TITLE="true"

#PLUGINS
plugins=(git zsh-autosuggestions zsh-syntax-highlighting history)

source $ZSH/oh-my-zsh.sh


export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
